GET http://localhost:8080/followers

###
POST http://localhost:8080/followers HTTP/1.1
Content-Type: application/json

{
    "UserUuid" : "583e9b46-e640-4db9-9b7d-26dec96b6b25",
    "followerId" : "583e9b46-e640-4db9-9b7d-26dec96b6b25"
}

###
POST https://squicker.herokuapp.com/datas HTTP/1.1
Content-Type: application/json

{
    "bloodSugar" : "ok",
    "weight" : "ok",
    "mood" : "ok",
    "appetite" : "ok",
    "patientUuid": "3421d7cf-c8cd-4cde-9a33-92a0e605fc88"

}

###
DELETE http://localhost:8080/likes/46dff96e-850e-4d85-92f0-0579b95ea4ae HTTP/1.1