GET http://localhost:8080/likes

###
POST http://localhost:8080/likes HTTP/1.1
Content-Type: application/json

{
    "UserUuid" : "3250e6c6-5535-4543-b84c-542789c5e69c",
    "MessageUuid": "7c93ef27-1a7d-41b8-a2ee-bc39f0c7c94f"
}

###
POST https://squicker.herokuapp.com/datas HTTP/1.1
Content-Type: application/json

{
    "bloodSugar" : "ok",
    "weight" : "ok",
    "mood" : "ok",
    "appetite" : "ok",
    "patientUuid": "3421d7cf-c8cd-4cde-9a33-92a0e605fc88"

}

###
GET http://localhost:8080/likes/fdc9bc48-9f82-4dcc-b2e8-19b355847a18 HTTP/1.1