GET http://localhost:8080/likes

###
POST http://localhost:8080/likes HTTP/1.1
Content-Type: application/json

{
    "UserUuid" : "c54198b4-a236-4557-9037-c3c61e627702",
    "PostUuid": "6c7d8c40-b21c-40de-913c-873e622e7434"
}

###
POST https://squicker.herokuapp.com/datas HTTP/1.1
Content-Type: application/json

{
    "bloodSugar" : "ok",
    "weight" : "ok",
    "mood" : "ok",
    "appetite" : "ok",
    "patientUuid": "3421d7cf-c8cd-4cde-9a33-92a0e605fc88"

}

###
DELETE http://localhost:8080/likes/46dff96e-850e-4d85-92f0-0579b95ea4ae HTTP/1.1