### GET ALL
GET http://localhost:8081/messages

### POST ONE
POST http://localhost:8081/messages HTTP/1.1
Content-Type: application/json

{
    "content" : "cczzczc",
    "UserUuid" : "bcb1a04b-295a-4533-b9c9-f404c66b955e"
}


