### GET ALL
GET http://localhost:8080/messages

### POST ONE
POST http://localhost:8080/messages HTTP/1.1
Content-Type: application/json

{
    "content" : "cczzczc",
    "UserUuid" : "68aa8ba2-8d8d-4e17-bf19-d4cf5e9ef46e"
}


