### GET ALL
GET https://mychatappmessenger.herokuapp.com/messages

### POST ONE
PUT https://mychatappmessenger.herokuapp.com/messages/216c9ae9-db65-42bc-9c4c-40138e2e9eed HTTP/1.1
Content-Type: application/json

{
    "likes" : 1
}

